force-app/main/default/objects/Account/fields/AverageSalaryOfContacts__c.field-meta.xml
<CustomField>
    <fullName>AverageSalaryOfContacts__c</fullName>
    <label>Average Salary Of Contacts</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler implements ITriggerHandler {
    public AccountTriggerHandler() {}

    public static void beforeUpdate(List<Account> newList, List<Account> oldList){
        if(newList[0].NumberOfContacts__c != oldList[0].NumberOfContacts__c){
            newList[0].NumberOfContacts__c = oldList[0].NumberOfContacts__c;
        }
        if(newList[0].AverageSalaryOfContacts__c != oldList[0].AverageSalaryOfContacts__c){
            newList[0].AverageSalaryOfContacts__c = oldList[0].AverageSalaryOfContacts__c;
        }
    }
}